application: socialmetrics
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: templates/static
  
- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin

- url: /admin/.*
  script: main.py
  login: admin

- url: /.*
  script: main.py

builtins:
- datastore_admin: on
